previewsEnabled: true
services:
  - type: web
    name: Create React App Demo
    env: static
    buildCommand: yarn build
    staticPublishPath: ./build
    domains:
      - foo.thebeynons-seconddomain.uk
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
